# https://www.python.org/dev/peps/pep-0518/#file-format

# https://docs.astral.sh/ruff/settings/
[tool.ruff]
line-length = 132
target-version = "py311"

[tool.ruff.lint]
fixable = ["ALL"]

# https://docs.astral.sh/ruff/rules/
select = [
  "ASYNC",
  "ARG",
  "BLE",
  "C",
  "E",
  "F",
#  "FBT",
  "FLY",
  "FURB",
  "I",
  "N",
  "PERF",
  "PGH",
#  "PL",
  "Q",
  "R",
  "RUF",
  "S",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  "C901",
  "S602",
  "S607",
]

[tool.ruff.lint.per-file-ignores]
"**/test.py" = [
  "S101",
  ]

[tool.ruff.lint.mccabe]
max-complexity = 10
