# The original upstream Gemfile is: https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile
# To update, loosely version these packages, then run 'make update-fluentd-gemfile.lock'

source 'https://rubygems.org'

### Upstream packages
gem 'activesupport', '~>6.1'
gem 'elasticsearch', '<7.14'
gem 'elasticsearch-xpack', '<7.14'
gem 'fluent-plugin-concat', '~>2.5'
gem 'fluent-plugin-detect-exceptions', '~>0.0'
gem 'fluent-plugin-elasticsearch', '~>4.3'
gem "fluent-plugin-cloudwatch-logs", "~>0.14.2"
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.7'
gem 'fluent-plugin-multi-format-parser', '~>1.0'
gem 'fluent-plugin-prometheus', '~>2.0'
gem 'fluent-plugin-systemd', '~>1.0'
gem 'fluentd', '>=1.13'
gem 'oj', '~>3.10'

### Packages not included with upstream
gem 'fluent-plugin-rewrite-tag-filter', '~>2.4'
gem 'fluent-plugin-s3', '~>1.6'
gem 'json', '~>2.5'
gem 'rake', '~>13.0'
gem 'fluent-plugin-newrelic', '~>1.2'
