# The original upstream Gemfile is: https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile
# We have loosely versioned those, and let `bundle update` pin the most recent
# compatible versions inside of Gemfile.lock

source 'https://rubygems.org'

### Upstream packages
gem 'activesupport', '~>6.1'
gem 'elasticsearch-xpack', '~>7.9'
gem 'fluent-plugin-concat', '~>2.5'
gem 'fluent-plugin-detect-exceptions', '~>0.0'
gem 'fluent-plugin-elasticsearch', '~>4.3'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.7'
gem 'fluent-plugin-multi-format-parser', '~>1.0'
gem 'fluent-plugin-prometheus', '~>1.8'
gem 'fluent-plugin-systemd', '~>1.0'
gem 'fluentd', '~>1.13'
gem 'oj', '~>3.10'

### Packages not included with upstream
gem 'fluent-plugin-rewrite-tag-filter', '~>2.4'
gem 'fluent-plugin-s3', '~>1.6'
gem 'json', '~>2.5'
gem 'rake', '~>12.3'
gem 'yajl-ruby', '~>1.4' # CVE-2017-16516
