# To upgrade this image, replace the contents below with the following Gemfile:
# https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile

source 'https://rubygems.org'

gem 'activesupport', '6.0.3.4'
gem 'json', '>=2.3.0'
gem 'rake', '>= 12.3.3'
gem 'elasticsearch-xpack', '7.9.0' 
gem 'fluentd', '1.12.0'
gem 'fluent-plugin-concat', '2.4.0'
gem 'fluent-plugin-detect-exceptions', '0.0.13'
gem 'fluent-plugin-elasticsearch', '4.2.2'
gem 'fluent-plugin-kubernetes_metadata_filter', '2.5.2'
gem 'fluent-plugin-multi-format-parser', '1.0.0'
gem 'fluent-plugin-prometheus', '1.8.4'
gem 'fluent-plugin-systemd', '1.0.2'
gem 'fluent-plugin-rewrite-tag-filter', '~>2.2.0'
gem 'fluent-plugin-s3', '~>1.3.0'
gem 'oj', '3.10.15'

# to upgrade goto and sync with current Gemfile
# https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile


### Not included with upstream contents
gem 'yajl-ruby', '~>1.4.1' # CVE-2017-16516
