{
 "title": "Airflow Scheduler",
 "tags": [ "airflow" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(airflow_scheduler_heartbeat, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Scheduler Heartbeat",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_scheduler_heartbeat{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Ongoing Local Task Jobs",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_localtaskjob_start{deployment=~\"$deployment\"} - airflow_localtaskjob_end{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Zombies Killed",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_zombies_killed{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Dagbag Size",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_dagbag_size{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Collect DAGs",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_collect_dags{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "DAG Bag Import Errors",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_dagbag_import_errors{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "DAG parsing processes",
   "type": "grafana-singlestat-panel",
   "description": "Number of currently running DAG parsing processes",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_dag_processing_processes{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Ongoing Scheduler Jobs",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_schedulerjob_start{deployment=~\"$deployment\"} - airflow_schedulerjob_end{deployment=~\"$deployment\"}) "
    }
   ]
  },
  {
   "title": "Processor Timeouts",
   "type": "grafana-singlestat-panel",
   "description": "Number of file processors that have been killed due to taking too long",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_dag_processing_processor_timeouts{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Scheduler Tasks Executable",
   "type": "grafana-singlestat-panel",
   "description": "Number of Executable TaskInstance",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_scheduler_tasks_executable{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Scheduler Tasks Pending",
   "type": "grafana-singlestat-panel",
   "description": "Number of TaskInstance pending execution by Scheduler",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_scheduler_tasks_pending{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Scheduler Tasks Running",
   "type": "grafana-singlestat-panel",
   "description": "Number of Tasks in Executor",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_scheduler_tasks_running{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Scheduler Tasks Starving",
   "type": "grafana-singlestat-panel",
   "description": "Number of Tasks starving in executor as there are no open slots in the pool",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_scheduler_tasks_starving{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Successful Task Instances",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_ti_successes{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Failed Task Instances",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_ti_failures{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Operator Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(airflow_operator_successes{deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Operator Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(airflow_operator_failures{deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat Rate",
   "type": "timeseries",
   "description": "TimeSeries Graph showing rate of Scheduler Heartbeart Rate per min. 0 indicate Scheduler outage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat{deployment=~\"$deployment\", type=\"counter\"}[1m])*60",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Tasks in Scheduler Loop",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(airflow_scheduler_tasks_executable{deployment=~\"$deployment\"})",
     "legendFormat": "Ready to Run"
    },
    {
     "expr": "sum(airflow_scheduler_tasks_pending{deployment=~\"$deployment\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(airflow_scheduler_tasks_running{deployment=~\"$deployment\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(airflow_scheduler_tasks_starving{deployment=~\"$deployment\"})",
     "legendFormat": "Starving"
    }
   ]
  },
  {
   "title": "SchedulerJob",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(airflow_schedulerjob_start{deployment=~\"$deployment\"})",
     "legendFormat": "Job Start"
    },
    {
     "expr": "-sum(airflow_schedulerjob_end{deployment=~\"$deployment\"})",
     "legendFormat": "Job End"
    }
   ]
  },
  {
   "title": "Dependency Check Timing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(airflow_dagrun_dependency_check_sum{deployment=~\"$deployment\"}[3m])\n/\nrate(airflow_dagrun_dependency_check_count{deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{ dag_id }}"
    }
   ]
  }
 ]
}