{
 "title": "Airflow Database Activity",
 "tags": [ "airflow" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(pgbouncer_exporter_pools_active_clients, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Database Connections",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_exporter_database_current_connections{name!=\"pgbouncer\", deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Total Waiting Clients",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_exporter_pools_waiting_clients{database!=\"pgbouncer\", deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_exporter_database_current_connections{name!=\"pgbouncer\", deployment=~\"$deployment\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Waiting Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_exporter_pools_waiting_clients{database!=\"pgbouncer\", deployment=~\"$deployment\"}",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Active Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_exporter_pools_active_clients{database!=\"pgbouncer\", deployment=~\"$deployment\"}",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_exporter_stats_total_query_time{database!=\"pgbouncer\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_exporter_stats_total_received{database!=\"pgbouncer\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_exporter_stats_total_sent{database!=\"pgbouncer\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "{{ database }}"
    }
   ]
  }
 ]
}