{
 "title": "Airflow Deployment Utilizations",
 "tags": [ "airflow" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_pod_info, release)"
   }
  ]
 },
 "panels": [
  {
   "title": "At a Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Status",
     "type": "singlestat",
     "description": "Indication of whether all deployment containers are running.",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by (release) (\n  kube_pod_container_status_running{namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"}\n) -\ncount by (release) (\n  kube_pod_container_status_running{namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"}\n)"
      }
     ]
    },
    {
     "title": "Scheduler Heartbeat",
     "type": "singlestat",
     "description": "Indication of whether the scheduler is up and running its loop. An value of \"Unknown\" means that the airflow image is running an older version.",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "round(rate(airflow_scheduler_heartbeat{deployment=~\"$deployment\", type=\"counter\"}[1m]) * 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Pods",
     "type": "singlestat",
     "description": "Maximum total pods allowed. Each airflow deployment namespace has resource quotas applied.",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"pods\", type=\"hard\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Max CPU",
     "type": "singlestat",
     "description": "Maximum total CPU limits allowed. Each airflow deployment namespace has resource quotas applied.",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "singlestat",
     "description": "Maximum total memory limits allowed. Each airflow deployment namespace has resource quotas applied.",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Running Pods",
     "type": "singlestat",
     "description": "Percentage of total pods in use currently. Each airflow deployment namespace has resource quotas applied.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"pods\", type=\"used\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})\n/\nsum(kube_resourcequota{resource=\"pods\", type=\"hard\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})*100"
      }
     ]
    },
    {
     "title": "Reserved CPU",
     "type": "singlestat",
     "description": "Percentage of total CPU limits in use currently. Each airflow deployment namespace has resource quotas applied.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})\n/\nsum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})*100"
      }
     ]
    },
    {
     "title": "Reserved Memory",
     "type": "singlestat",
     "description": "Percentage of total memory limits in use currently. Each airflow deployment namespace has resource quotas applied.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})\n/\nsum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\", namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})*100"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Status",
     "type": "table",
     "description": "Status of containers that make up an airflow deployment. A failing status here will make the deployment above show Unhealthy.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sort_desc(max by (container, pod, reason) (\n  max by (container, pod) (\n    sort_desc(kube_pod_container_status_waiting{namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"})\n  ) or\n  max by (container, reason) (\n    sort_desc(kube_pod_container_status_waiting_reason{namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"}==1)\n  ) or\n  max by (container, reason) (\n    sort_desc(kube_pod_container_status_terminated_reason{namespace=~\".*-.*-.*-[0-9]{4}\", release=~\"$deployment\"}==1)\n  )\n))\n"
      }
     ]
    }
   ]
  },
  { "title": "Requests, Limits, Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "scheduler cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(scheduler)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(scheduler)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(scheduler)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(scheduler)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "scheduler mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(scheduler)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(scheduler)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(scheduler)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(scheduler)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  },
  {
   "title": "webserver cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(webserver)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(webserver)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(webserver)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(webserver)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "webserver mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(webserver)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(webserver)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(webserver)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(webserver)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  },
  {
   "title": "pg_bouncer cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(pgbouncer)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(pgbouncer)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(pgbouncer)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(pgbouncer)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "pg_bouncer mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(pgbouncer)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(pgbouncer)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(pgbouncer)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(pgbouncer)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  },
  {
   "title": "statsd cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(statsd)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(statsd)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(statsd)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(statsd)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "statsd mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(statsd)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(statsd)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(statsd)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(statsd)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  },
  {
   "title": "redis cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(redis)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(redis)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(redis)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(redis)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "redis mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(redis)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(redis)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(redis)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(redis)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  },
  {
   "title": "flower cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(flower)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(flower)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(flower)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(flower)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "flower mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(flower)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(flower)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(flower)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(flower)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  },
  {
   "title": "worker cpu",
   "type": "graph",
   "description": "CPU usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"cpu\", container=~\".*(worker)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"cpu\", container=~\".*(worker)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{component_name=~\".*(worker)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{component_name=~\".*(worker)\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "worker mem",
   "type": "graph",
   "description": "Mem usage, requests, and limits",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{release=~\"$deployment\", resource=\"memory\", container=~\".*(worker)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{release=~\"$deployment\", resource=\"memory\", container=~\".*(worker)\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "container_memory_usage_bytes{component_name=~\".*(worker)\", deployment=~\"$deployment\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(worker)\", deployment=~\"$deployment\"}",
     "legendFormat": "real memory"
    }
   ]
  }
 ]
}