{
 "title": "Airflow Resource Utilization",
 "tags": [ "airflow" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "description": "CPU as per container expressed as percentage of given CPU limit.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(rate(container_cpu_usage_seconds_total{deployment=~\"$deployment\", pod_name!~\".*-worker-.*\",component_name != \"POD\",image!=\"\"}[3m])) by (pod_name, container_name, component_name, namespace, short_name)/\n  sum(container_spec_cpu_quota{deployment=~\"$deployment\", pod_name!~\".*-worker-.*\", component_name != \"POD\",image!=\"\"}/container_spec_cpu_period{deployment=~\"$deployment\", pod_name!~\".*-worker-.*\", component_name != \"POD\",image!=\"\"}) by (pod_name, container_name, component_name, namespace, short_name)*100,\n  \"short_name\",\n  \"$1\",\n  \"pod_name\",\n  \"^[[deployment]]-(.*)$\"\n)",
     "legendFormat": "{{pod_name}} ({{container_name}})"
    }
   ]
  },
  {
   "title": "Workers CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{deployment=~\"$deployment\", pod_name=~\".*-worker-.*\",component_name != \"POD\",image!=\"\", container_name != \"istio-proxy\"}[3m]))\n  by (pod_name, container_name, short_name, namespace)\n/\nsum(container_spec_cpu_quota{deployment=~\"$deployment\", pod_name=~\".*-worker-.*\", component_name != \"POD\",image!=\"\", container_name != \"istio-proxy\"} / container_spec_cpu_period{deployment=~\"$deployment\", pod_name=~\".*-worker-.*\", component_name != \"POD\",image!=\"\", container_name != \"istio-proxy\" }) by (pod_name, container_name, short_name, namespace) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "description": "Memory as per container expressed as percentage of given Memory limit.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{component_name=~\".*(scheduler|webserver|flower|istio-proxy)\", deployment=~\"$deployment\"} / \ncontainer_spec_memory_limit_bytes{component_name=~\".*(scheduler|webserver|flower|istio-proxy)\", deployment=~\"$deployment\"} * 100",
     "legendFormat": "{{pod_name}} ({{container_name}})"
    }
   ]
  },
  {
   "title": "Worker Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{component_name=\"worker\", deployment=~\"$deployment\"} / container_spec_memory_limit_bytes{component_name=\"worker\", deployment=~\"$deployment\"} * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Workers Network Bytes Received",
   "type": "timeseries",
   "description": "Sum of network bytes received by deployment",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{component_name=\"worker\", deployment=~\"$deployment\"}[3m])) by (deployment)",
     "legendFormat": "{{deployment}} "
    }
   ]
  },
  {
   "title": "Workers Network Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{component_name=\"worker\", deployment=~\"$deployment\"}[3m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Component Network Bytes Received",
   "type": "timeseries",
   "description": "Airflow Pod Bytes Received, not including workers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{component_name!~\"istio-proxy|worker\", deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{deployment}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Component Network Bytes Sent",
   "type": "timeseries",
   "description": "Airflow components network bytes sent, not including the workers",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{component_name!~\"istio-proxy|worker\", deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{deployment}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "timeseries",
   "description": "This shows the amount of ephemeral storage each component is using.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{deployment=~\"$deployment\"} * 100 / container_fs_limit_bytes{deployment=~\"$deployment\"}",
     "legendFormat": "{{ pod_name }} ({{ component_name }})"
    }
   ]
  }
 ]
}