{
 "title": "Airflow State",
 "tags": [ "airflow" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_pod_info, release)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Namespaces",
   "type": "grafana-singlestat-panel",
   "description": "Namespaces that are up and hosting an airflow deployment. This will be 0 in single namespace mode.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{namespace=~\".*-.*-.*-[0-9]{4}\", phase=\"Active\"})"
    }
   ]
  },
  {
   "title": "Terminating Namespaces",
   "type": "grafana-singlestat-panel",
   "description": "Namespaces that are in terminating state. Most likely because a deployment has been shut down. This will be 0 in single namespace mode.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{namespace=~\".*-.*-.*-[0-9]{4}\", phase=\"Terminating\"})"
    }
   ]
  },
  {
   "title": "Scheduler Generations (Deploy Count)",
   "type": "grafana-singlestat-panel",
   "description": "Revision count for the Scheduler. Generally the amount of times code has been pushed.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_observed_generation{deployment=~\".*-scheduler\", release=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "grafana-singlestat-panel",
   "description": "Active Kubernetes Deployments. Most Airflow components are a deployment.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(kube_deployment_spec_replicas{release=~\"$deployment\"}))"
    }
   ]
  },
  {
   "title": "Active Stateful Sets",
   "type": "grafana-singlestat-panel",
   "description": "Active StatefulSets for an Airflow deployment.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(kube_statefulset_status_replicas{release=~\"[[deployment]]\"}))"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "description": "Total pods that are in the running state.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{release=~\"$deployment\", phase=\"Running\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Pods Ready",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of Pods that have been scheduled and are currently running.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{condition=\"true\", release=~\"$deployment\"})\n/\nsum(kube_pod_status_ready{condition=\"true\", release=~\"$deployment\"})*100"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "timeseries",
   "description": "Total containers in the Running state.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{release=~\"$deployment\"})",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max CPU Requests",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total CPU requests allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Max CPU Limits",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total CPU limits allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Max Pods",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total pods allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"pods\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Max Mem Requests",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total memory requests allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Max Mem Limits",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total memory limits allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total CPU requests in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total CPU limits in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total pods in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"pods\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"pods\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total memory requests in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total memory limits in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Deployment Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment Status",
   "type": "table",
   "description": "Status of Airflow deployments. Healthy if everything is up and running, and Unhealthy if there is a problem or during code pushes.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sort(\n sum by (release) (\n  sum by (release) (\n  kube_pod_container_status_running{release=~\"$deployment\", container!=\"airflow-cleanup-pods\"}\n ) - \n count by (release) (\n  kube_pod_container_status_running{release=~\"$deployment\", container!=\"airflow-cleanup-pods\"}\n  )\n )\n)"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "table",
   "description": "Status of containers that make up an airflow deployment. A failing status here will make the deployment above show Unhealthy.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sort_desc(max by (container, pod, reason) (\n max by (container, pod) (\n sort_desc(kube_pod_container_status_waiting{release=~\"$deployment\", container!=\"airflow-cleanup-pods\"})\n ) or\n max by (container, reason) (\n sort_desc(kube_pod_container_status_waiting_reason{release=~\"$deployment\"}==1)\n ) or\n max by (container, reason) (\n sort_desc(kube_pod_container_status_terminated_reason{release=~\"$deployment\", container!=\"airflow-cleanup-pods\"}==1)\n )\n))\n"
    }
   ]
  }
 ]
}