{
 "title": "Airflow Deployment Overview",
 "tags": [ "airflow" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_pod_info, release)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "At a Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment Status",
   "type": "grafana-singlestat-panel",
   "description": "Indication of whether all deployment containers are running.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (release) (\n  kube_pod_container_status_running{release=~\"$deployment\", container=~\".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)\"} and on(pod,namespace) kube_pod_labels{label_dag_id=\"\"}\n) -\ncount by (release) (\n  kube_pod_container_status_running{release=~\"$deployment\", container=~\".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)\"} and on(pod,namespace) kube_pod_labels{label_dag_id=\"\"}\n)"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat",
   "type": "grafana-singlestat-panel",
   "description": "Indication of whether the scheduler is up and running its loop. An value of \"Unknown\" means that the airflow image is running an older version.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat{deployment=~\"$deployment\", type=\"counter\"}[1m])"
    }
   ]
  },
  {
   "title": "Quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Pods",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total pods allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"pods\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Max CPU",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total CPU limits allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "grafana-singlestat-panel",
   "description": "Maximum total memory limits allowed. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total pods in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"pods\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"pods\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Reserved CPU",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total CPU limits in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Reserved Memory",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of total memory limits in use currently. Each airflow deployment namespace has resource quotas applied.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})\n/\nsum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\", release=~\"$deployment\", resourcequota=~\"$deployment-resource-quota\"})*100"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successful Tasks",
   "type": "grafana-singlestat-panel",
   "description": "Total successful tasks.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_ti_successes{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "grafana-singlestat-panel",
   "description": "Total failed tasks.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_ti_failures{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Dagbag Size",
   "type": "grafana-singlestat-panel",
   "description": "Amount of DAGs the scheduler is processing.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_dagbag_size{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Zombies Killed",
   "type": "grafana-singlestat-panel",
   "description": "Tasks that have not sent a heartbeat in a while.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_zombies_killed{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Task Success Rate",
   "type": "timeseries",
   "description": "Rate of task successes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(airflow_operator_successes{deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Task Failure Rate",
   "type": "timeseries",
   "description": "Rate of task failures.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(airflow_operator_failures{deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat Rate",
   "type": "timeseries",
   "description": "TimeSeries Graph showing rate of Scheduler Heartbeart Rate per min. 0 indicate Scheduler outage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat{deployment=~\"$deployment\", type=\"counter\"}[1m])*60",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Database Connections",
   "type": "grafana-singlestat-panel",
   "description": "Total connections to the backend database.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_exporter_database_current_connections{name!=\"pgbouncer\", deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Total Waiting Clients",
   "type": "grafana-singlestat-panel",
   "description": "Number of airflow clients waiting for a connection to the backend database.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_exporter_pools_waiting_clients{database!=\"pgbouncer\", deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Actual CPU utilization across deployment containers.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(  sum(rate(container_cpu_usage_seconds_total{deployment=~\"$deployment\", component_name != \"POD\",image!=\"\", container_name!=\"istio-proxy\"}[3m])) by (pod_name, container_name, component_name, namespace, short_name)/  sum(container_spec_cpu_quota{deployment=~\"$deployment\",  component_name != \"POD\",image!=\"\", container_name!=\"istio-proxy\"}/container_spec_cpu_period{deployment=~\"$deployment\",  component_name != \"POD\",image!=\"\", container_name!=\"istio-proxy\"}) by (pod_name, container_name, component_name, namespace, short_name)*100,  \"short_name\",  \"$1\",  \"pod_name\",  \"^[[deployment]]-(.*)$\")",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Actual memory utilization across deployment containers.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{deployment=~\"$deployment\", component_name != \"POD\",image!=\"\", container_name!=\"istio-proxy\"} * 100 / container_spec_memory_limit_bytes{deployment=~\"$deployment\", component_name != \"POD\",image!=\"\", container_name!=\"istio-proxy\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "description": "Received data across deployment containers.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{component_name=~\".*(scheduler|webserver|worker|flower|redis|pgbouncer|statsd)\", deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "description": "Transmitted data across deployment containers.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{component_name=~\".*(scheduler|webserver|worker|flower|redis|pgbouncer|statsd)\", deployment=~\"$deployment\"}[3m])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Core Container Status",
   "type": "table-old",
   "description": "Status of containers that make up an airflow deployment. A failing status here will make the deployment above show Unhealthy.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sort_desc(max by (container, pod, reason) (  \nmax by (container, pod) ( \nsort_desc(kube_pod_container_status_waiting{release=~\"$deployment\", container=~\".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)\"} \nand on(pod,namespace) kube_pod_labels{label_dag_id=\"\"})  )   \nor  max by (container, reason) (      sort_desc(kube_pod_container_status_waiting_reason{release=~\"$deployment\", container=~\".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)\"}==1 and on(pod,namespace) kube_pod_labels{label_dag_id=\"\"}) )   \nor  max by (container, reason) (    sort_desc(kube_pod_container_status_terminated_reason{release=~\"$deployment\", container=~\".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)\"}==1 and on(pod,namespace) kube_pod_labels{label_dag_id=\"\"}) )))"
    }
   ]
  },
  {
   "title": "Task Container Status",
   "type": "table-old",
   "description": "Kubernetes executor pods only",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sort_desc(max by (container, pod, reason) (\n  max by (container, pod) (    \n  sort_desc(kube_pod_container_status_waiting{release=~\"$deployment\"} and on(pod,namespace) kube_pod_labels{label_dag_id!=\"\"})  ) \n  or  max by (container, reason) (    \n  sort_desc(kube_pod_container_status_waiting_reason{release=~\"$deployment\"}==1 and on(pod,namespace) kube_pod_labels{label_dag_id!=\"\"}) ) \n  or  max by (container, reason) (    sort_desc(kube_pod_container_status_terminated_reason{release=~\"$deployment\"}==1 and on(pod,namespace) kube_pod_labels{label_dag_id!=\"\"}) )))"
    }
   ]
  }
 ]
}