{
 "title": "Elasticsearch",
 "tags": [
  "elasticsearch",
  "platform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Quick Numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Nodes",
   "type": "grafana-singlestat-panel",
   "description": "Total Elasticsearch Pods. Masters, Clients, Data.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes)/count(elasticsearch_cluster_health_number_of_nodes)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "grafana-singlestat-panel",
   "description": "Total memory limits of all Elasticsearch pods.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=~\"(es-master|es-data|es-client)\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "grafana-singlestat-panel",
   "description": "Total memory free on all Elasticsearch pods.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=~\"(es-master|es-data|es-client)\"})\n-\nsum(container_memory_working_set_bytes{container_name=~\"(es-master|es-data|es-client)\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of all Elasticsearch pods.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=~\"(es-master|es-data|es-client)\"}[3m])",
     "legendFormat": "{{ container_name }} {{ component_instance }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents Indexed",
   "type": "timeseries",
   "description": "Total documents indexed.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs)",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "timeseries",
   "description": "Total size of Elasticsearch index.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes)",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "timeseries",
   "description": "Data volume usage across all Elasticsearch pods.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data-.*-elasticsearch-.*\"}",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Available",
   "type": "timeseries",
   "description": "Data volume space available across all Elasticsearch pods.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-.*-elasticsearch-.*\"}",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread Pools",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{ type }}"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "RX/TX Bytes Rate 5m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_transport_rx_size_bytes_total[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(elasticsearch_transport_tx_size_bytes_total[5m])) * -1",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum[1m])",
     "legendFormat": "{{ name }} {{ gc }}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{type}}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{type!=\"management\"}[5m])",
     "legendFormat": "{{ name }} {{ type }}"
    }
   ]
  }
 ]
}