{
 "title": "Node Capacity Utilization",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Node Count by Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (kube_node_info{node=~\"gke-prod-cluster-terraform-2020011920-.*\"})",
     "legendFormat": "Astron Nodes"
    },
    {
     "expr": "count (kube_node_info{node=~\"gke-prod-cluster-prod-mt-.*\"})",
     "legendFormat": "MT Nodes"
    },
    {
     "expr": "count (kube_node_info{node=~\"gke-prod-cluster-terraform-2020020819-.*\"})",
     "legendFormat": "Dyn Nodes"
    }
   ]
  },
  {
   "title": "Astro Pool CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores {node=~\"gke-prod-cluster-terraform-2020011920-.*\"} / 16 * 100)"
    }
   ]
  },
  {
   "title": "Astro Pool MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes {node=~\"gke-prod-cluster-terraform-2020011920-.*\"} / (58 * 1024 * 1024 * 1024) * 100)"
    }
   ]
  },
  {
   "title": "MT Pool CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores {node=~\"gke-prod-cluster-prod-mt-.*\"} / 16 * 100)"
    }
   ]
  },
  {
   "title": "MT Pool MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes {node=~\"gke-prod-cluster-prod-mt-.*\"} / (58 * 1024 * 1024 * 1024) * 100)"
    }
   ]
  },
  {
   "title": "Dyn Pool CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores {node=~\"gke-prod-cluster-terraform-2020020819-.*\"} / 16 * 100)"
    }
   ]
  },
  {
   "title": "Dyn Pool MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes {node=~\"gke-prod-cluster-terraform-2020020819-.*\"} / (58*1024*1024*1024) * 100)"
    }
   ]
  }
 ]
}