{
 "title": "kubed",
 "description": "kubed in the astronomer namespace",
 "tags": [
  "kubed",
  "platform",
  "astronomer platform"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "minutes",
    "label": "Minutes",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "container_memory_rss bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(container_memory_rss{namespace=\"astronomer\", component_name=\"astronomer-kubed\", container!=\"POD\", container!=\"istio-proxy\"})[${minutes}:])",
     "legendFormat": "container_memory_rss {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "kube_pod_container_resource_limits_memory_bytes"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "kube_pod_container_resource_requests_memory_bytes"
    }
   ]
  },
  {
   "title": "container_memory_working_set_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(container_memory_working_set_bytes{namespace=\"astronomer\", component_name=\"astronomer-kubed\", container!=\"POD\", container!=\"istio-proxy\"})[${minutes}:])",
     "legendFormat": "container_memory_working_set_bytes: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "kubed container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"astronomer\", container_name=\"astronomer-kubed\"}[${minutes}])",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "kubed POD network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"astronomer\", component_name=\"kubed\"}[${minutes}])",
     "legendFormat": "{{ pod_name }} rx"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"astronomer\", component_name=\"kubed\"}[${minutes}])",
     "legendFormat": "{{ pod_name }} tx"
    }
   ]
  },
  {
   "title": "kubed container restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"astronomer\", container=\"astronomer-kubed\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}