{
 "title": "Kubernetes Pods",
 "description": "Kubernetes Pods (Prometheus)",
 "tags": [
  "airflow",
  "platform"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod=\"$pod\"}, pod_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod IP Address",
   "type": "text",
   "options": { "content": "# $Pod_ip" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Status",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "scalar(kube_pod_status_phase{pod=\"$pod\", phase=\"Failed\"}*1) + scalar(kube_pod_status_phase{pod=\"$pod\", phase=\"Pending\"}*2) + scalar(kube_pod_status_phase{pod=\"$pod\", phase=\"Running\"}*3) + scalar(kube_pod_status_phase{pod=\"$pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$pod\", phase=\"Unknown\"}*5)"
    }
   ]
  },
  {
   "title": "Pod Container",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "content": "# $container" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container restarts",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$pod.*$\", container=~\"$container.*$\"}"
    }
   ]
  },
  {
   "title": "Pod memory working bytes",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\", pod_name=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_working_set_bytes{pod_name=\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=\"$pod\"}[1m]))",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=\"$pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "- sort_desc(sum by (pod_name) (rate(container_network_transmit_bytes_total{pod_name=\"$pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}