{
 "title": "Platform Overview 2021-11-11",
 "tags": [ "platform" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  { "title": "Data Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Prometheus Data Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-.*-prometheus-.*\"})"
    }
   ]
  },
  {
   "title": "Registry Data Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-.*-registry-.*\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch Data Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-.*elasticsearch-data-.*\"})"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Prometheus Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-.*-prometheus-.*\"}) / sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-.*-prometheus-.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Registry Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-.*-registry-.*\"}) / sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-.*-registry-.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Elasticsearch Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-.*-elasticsearch-data-.*\"}) / sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-.*-elasticsearch-data-.*\"}) * 100"
    }
   ]
  },
  { "title": "Platform Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Platform Availability",
   "type": "graph",
   "description": "Percent of HTTP responses not 5xx, as a moving average over the last 24 hours. 503 from webserver is ignored because it's expected when the airflow webserver is coming up.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_ingress_controller_requests{status!~\"5.*\"}[1d])) + sum(increase(nginx_ingress_controller_requests{service=~\".*webserver\",status=\"503\"}[1d])) ) / sum(increase(nginx_ingress_controller_requests[1d]))",
     "legendFormat": "Availability"
    },
    { "expr": ".999", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "description": "The percent of responses with code 5xx as a percent of total requests , categorized by response code, measured every five minutes. 503 from webserver is ignored because it's expected when the airflow webserver is coming up.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum((increase(nginx_ingress_controller_requests{status=~\"5.[^3]\"}[5m]) or increase(nginx_ingress_controller_requests{service!~\".*webserver\", status=\"503\"}[5m]))) by (status) / ignoring(status) group_left sum(increase(nginx_ingress_controller_requests{}[5m])) > 0",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "description": "The percent of total requests that error with 4xx, categorized by response code, measured every five minutes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"4.*\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_ingress_controller_requests{}[5m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Platform Latency",
   "type": "graph",
   "description": "The 99th percentile of response times should be less than 1 second. The line shows the average over the past 24 hours.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=~\".*houston.*|.*app.*\", status!=\"101\"}[1d])))",
     "legendFormat": "p99 latency"
    },
    { "expr": "1", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Slow requests",
   "type": "graph",
   "description": "Where are the 99th percentile of latency requests coming from?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(nginx_ingress_controller_request_duration_seconds_bucket{host=~\".*houston.*|.*app.*\", status!=\"101\"}[5m]))",
     "legendFormat": "{{ host }} {{ method }} {{ status }}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "description": "How many requests are being handled per second, averaged over one minute.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{}[1m])) / 60",
     "legendFormat": "1 hour"
    }
   ]
  },
  {
   "title": "6-hour request volume",
   "type": "graph",
   "description": "How many requests have been handled on a 6h rolling window, compared to 1 week ago. This is useful to monitor platform growth.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{}[6h]))",
     "legendFormat": "6 hours"
    },
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{}[6h] offset 1w ))",
     "legendFormat": "6 hours (one week ago)"
    }
   ]
  },
  { "title": "Airflow Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Airflow Task Success Rate",
   "type": "graph",
   "description": "The average task success rate, categorized by percentile. For example, p50 means the success rate of the healthier half of the deployments, sorted by success rate. p100 means just the healthiest deployment. p0 means the average of all deployments.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(topk(1, (airflow_ti_successes) / (airflow_ti_failures + airflow_ti_successes)))",
     "legendFormat": "p100"
    },
    {
     "expr": "avg(topk(scalar(count(airflow_ti_successes) or on() vector(0)) / 4, (airflow_ti_successes) / (airflow_ti_failures + airflow_ti_successes)))",
     "legendFormat": "p75"
    },
    {
     "expr": "avg(topk(scalar(count(airflow_ti_successes) or on() vector(0)) / 2, (airflow_ti_successes) / (airflow_ti_failures + airflow_ti_successes)))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg(topk(scalar(count(airflow_ti_successes) or on() vector(0)) / 1.333, (airflow_ti_successes) / (airflow_ti_failures + airflow_ti_successes)))",
     "legendFormat": "p25"
    },
    {
     "expr": "avg((airflow_ti_successes) / (airflow_ti_failures + airflow_ti_successes))",
     "legendFormat": "p0"
    }
   ]
  },
  {
   "title": "1-day Airflow Task Volume",
   "type": "graph",
   "description": "The number of tasks that have run in the past 24 hours, categorized by success and failure. This does not account for the size or duration of tasks, but is still kind of useful for monitoring growth.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airflow_ti_successes[1d]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(increase(airflow_ti_failures[1d]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Airflow Scheduler Health",
   "type": "graph",
   "description": "The percent of Airflow schedulers that have received a heartbeat in the past 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(count(rate(airflow_scheduler_heartbeat{}[1m]) > 0) / count(rate(airflow_scheduler_heartbeat{}[1m])))",
     "legendFormat": "healthy"
    }
   ]
  },
  {
   "title": "Unhealthy Schedulers",
   "type": "graph",
   "description": "The deployments which do not have healthy schedulers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "clamp_min(rate(airflow_scheduler_heartbeat{}[1m]) <= 0, 1)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "DAG Parsing Time",
   "type": "graph",
   "description": "The average time to parse a DAG, categorized by percentile. For example, p50 means the bottom half of the deployments, sorted by parsing duration. p100 means just the deployment with the fastest average DAG parsing time. p0 means the average of all DAG parsing times. It is normalized across deployments, so each deployment has the same impact on the average, regardless of the number of DAGs a deployment has.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bottomk(1, (airflow_dag_processing_total_parse_time / airflow_dagbag_size) > 0 < +Inf))",
     "legendFormat": "p100"
    },
    {
     "expr": "avg(bottomk(scalar(count(airflow_dagbag_size > 0) or vector(0)) / 4, (airflow_dag_processing_total_parse_time / airflow_dagbag_size) > 0 < +Inf))",
     "legendFormat": "p75"
    },
    {
     "expr": "avg(bottomk(scalar(count(airflow_dagbag_size > 0) or vector(0)) / 2, (airflow_dag_processing_total_parse_time / airflow_dagbag_size) > 0 < +Inf))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg((airflow_dag_processing_total_parse_time / airflow_dagbag_size) > 0 < +Inf)",
     "legendFormat": "p0"
    }
   ]
  },
  {
   "title": "Airflow Webserver Restarts",
   "type": "graph",
   "description": "The number of Airflow webservers that have restarted in the past five minutes, categorized by namespace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (namespace) (increase(kube_pod_container_status_restarts_total{pod=~\".*webserver.*\"}[5m]))) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "DAG Parsing timeouts",
   "type": "graph",
   "description": "The number of DAG parsing timeouts in the past 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(airflow_dag_processing_processor_timeouts[5m])",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "5 Slowest DAG Parsing Deployments",
   "type": "graph",
   "description": "At any given time, list the 5 deployments with the slowest average DAG parsing time",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, (airflow_dag_processing_total_parse_time / airflow_dagbag_size) > 0 < +Inf)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Database Connections",
   "type": "graph",
   "description": "The number of currently active connections to the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (pgbouncer_exporter_database_current_connections)",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "PG Bouncer Active Clients",
   "type": "graph",
   "description": "The number of active clients, by deployment",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (pgbouncer_exporter_pools_active_clients)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "PG Bouncer Waiting Clients",
   "type": "graph",
   "description": "The number of waiting clients, by deployment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (pgbouncer_exporter_pools_waiting_clients)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}