{
 "title": "Prometheus",
 "description": "Overview of metrics from Prometheus 2.0.",
 "tags": [
  "prometheus",
  "platform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  {
   "title": "At a Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime [$interval]",
   "type": "grafana-singlestat-panel",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Currently Down",
   "type": "table-old",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",job=~\"$job\"} < 1"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "grafana-singlestat-panel",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Quick Numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Missed Iterations [$interval]",
   "type": "grafana-singlestat-panel",
   "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_evaluator_iterations_missed_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Iterations [$interval]",
   "type": "grafana-singlestat-panel",
   "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_evaluator_iterations_skipped_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tardy Scrapes [$interval]",
   "type": "grafana-singlestat-panel",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reload Failures [$interval]",
   "type": "grafana-singlestat-panel",
   "description": "Number of times the database failed to reload block data from disk.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Scrapes [$interval]",
   "type": "grafana-singlestat-panel",
   "description": "Sum of all skipped scrapes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) "
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data-.*-prometheus-.*\"}",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Persistent Volume Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-.*-prometheus-.*\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Percent of memory limit used by Prometheus. Hitting 100% will cause termination.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{component_name=\"prometheus\"} / container_spec_memory_limit_bytes{component_name=\"prometheus\"} * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failures and Errors",
   "type": "timeseries",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Reload"
    }
   ]
  },
  {
   "title": "Up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upness (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Series Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_created_total{instance=~\"$instance\"}[5m]) )",
     "legendFormat": "created"
    },
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{instance=~\"$instance\"}[5m]) )",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Appended Samples per Second",
   "type": "timeseries",
   "description": "Rate of total number of appended samples",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape Sync Total",
   "type": "timeseries",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_sync_total{job=~\"$job\",instance=~\"$instance\"}) by (scrape_job)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[2m])) by (scrape_job) * 1000",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Scrapes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "timeseries",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "exceeded sample limit"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "duplicate timestamp"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "out of bounds"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}) ",
     "legendFormat": "out of order"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Rule Evaluation Duration",
   "type": "timeseries",
   "description": "The duration of rule group evaluations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1000 * rate(prometheus_evaluator_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(prometheus_evaluator_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count{job=~\"$job\",instance=~\"$instance\"}[1m])) by (handler) > 0",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=~\"$job\",instance=~\"$instance\"}) by (slice)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule Evaluator Iterations",
   "type": "timeseries",
   "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_missed_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Missed"
    },
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_skipped_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Skipped"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Notifications Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_notifications_sent_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minutes Since Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$job\",instance=~\"$instance\"}) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Rate / 2m",
   "type": "timeseries",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}