{
 "title": "NATS Streaming Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "NATS Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NATS Streaming Channels Bytes/Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(nss_chan_bytes_total[5m])) by (channel) / 3"
    }
   ]
  },
  {
   "title": "NATS Streaming Server Total Bytes/Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(nss_server_bytes_total[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "NATS Streaming Channels Msgs/Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nss_chan_msgs_total[5m])) by (channel) / 3"
    }
   ]
  },
  {
   "title": "NATS Streaming Server Total Msgs/Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(rate(nss_server_msgs_total[5m])) by (instance))"
    }
   ]
  }
 ]
}