#!/bin/sh
# Map DATABASE_URL to PGBOUNCER_EXPORTER_CONNECTION_STRING
export PGBOUNCER_EXPORTER_CONNECTION_STRING="${PGBOUNCER_EXPORTER_CONNECTION_STRING:-$DATABASE_URL}"

exec pgbouncer_exporter "$@"
